-- AlterTable
ALTER TABLE "Todo" ALTER COLUMN "description" DROP NOT NULL,
ALTER COLUMN "description" DROP DEFAULT,
ALTER COLUMN "category" DROP NOT NULL,
ALTER COLUMN "category" SET DEFAULT 'sin categoria',
ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "dueHour" DROP NOT NULL,
ALTER COLUMN "dueDate" DROP NOT NULL;
